# Generated by Django 3.2.3 on 2021-05-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=50)),
                ('to_address', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
